### ISSUE TITLE
Add hover properties to ability

### ISSUE THREAD

**Issue by SinZ163** [ModDota/DotaUI#11]
Such as the cast range of the ability

**Comment by Perryvw** [comment]
Cast range seems to be done automatically either by the tooltip or the DOTAAbilityImage panel. What else?

**Comment by SinZ163** [comment]
When hovering, it adds a transparent gradient over the ability icon

**Comment by Perryvw** [comment]
Current hover effects:
- [x] Range indicator
- [x] Hover gradient 
- [x] Tooltip
