### ISSUE TITLE
Add cool-down indication.

### ISSUE THREAD

**Issue by SinZ163** [ModDota/DotaUI#3]
- [x] Involves shrinking the ability icon
- [x] having the number count down centered in the box
- [x] the radial covering the image.
- [x] small animation when off cooldown.

**Comment by SinZ163** [comment]
192b2e8e76a3df965b7e6e7680553a9cf76db3ea Implemented shrinking.

**Comment by Perryvw** [comment]
https://github.com/ModDota/DotaUI/commit/77989ec35001db454d22d9bdcdd165a0cf6ff078 Implements cooldown numbers in the ability panels.

**Comment by Perryvw** [comment]
Idea for shine animation:
Use animation (if it doesn't work transition?) on a panel with background gradient.

**Comment by SinZ163** [comment]
c449f131ef46c7d3c44cfc4dce35dfe4e546485b starts it, and ba359507097499bfbce073d4a7b230772e6c4f17 polishes it up.
