### ISSUE TITLE
Add keybind hotkeys

### ISSUE THREAD

**Issue by SinZ163** [ModDota/DotaUI#5]
Top left of ability frame, goes above everything else. (Legacy keys a potential problem and ULTIMATE / ATTRIBUTES handling)

**Comment by Perryvw** [comment]
https://github.com/ModDota/DotaUI/commit/6520101702ad46bbb2a6fa30a4936d29bcd4bda2

Legacy keys seem to be gone, the rest seems to be handled fine.
